USE [master]
GO

CREATE DATABASE [Y_N_module_3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Y_N_module_3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Y_N_module_3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Y_N_module_3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Y_N_module_3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Y_N_module_3] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Y_N_module_3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Y_N_module_3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Y_N_module_3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Y_N_module_3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Y_N_module_3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Y_N_module_3] SET ARITHABORT OFF 
GO

ALTER DATABASE [Y_N_module_3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Y_N_module_3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Y_N_module_3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Y_N_module_3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Y_N_module_3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Y_N_module_3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Y_N_module_3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Y_N_module_3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Y_N_module_3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Y_N_module_3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Y_N_module_3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Y_N_module_3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Y_N_module_3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Y_N_module_3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Y_N_module_3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Y_N_module_3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Y_N_module_3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Y_N_module_3] SET RECOVERY FULL 
GO

ALTER DATABASE [Y_N_module_3] SET  MULTI_USER 
GO

ALTER DATABASE [Y_N_module_3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Y_N_module_3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Y_N_module_3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Y_N_module_3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Y_N_module_3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Y_N_module_3] SET QUERY_STORE = OFF
GO

USE [Y_N_module_3]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Y_N_module_3] SET  READ_WRITE 
GO

