USE [master]
GO

/****** Object:  Database [Grocery_goods_store]    Script Date: 11.07.2018 16:59:23 ******/
CREATE DATABASE [Grocery_goods_store]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Grocery_goods_store', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Grocery_goods_store.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Grocery_goods_store_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Grocery_goods_store_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Grocery_goods_store] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Grocery_goods_store].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Grocery_goods_store] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET ARITHABORT OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Grocery_goods_store] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Grocery_goods_store] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Grocery_goods_store] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Grocery_goods_store] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET RECOVERY FULL 
GO

ALTER DATABASE [Grocery_goods_store] SET  MULTI_USER 
GO

ALTER DATABASE [Grocery_goods_store] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Grocery_goods_store] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Grocery_goods_store] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Grocery_goods_store] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Grocery_goods_store] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Grocery_goods_store] SET QUERY_STORE = OFF
GO

USE [Grocery_goods_store]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Grocery_goods_store] SET  READ_WRITE 
GO

